export const metadataKeyword: Array<string> = [
  "zarb",
  "zarb beat",
  "zarbbeat",
  "beat",
  "vercel",
  "music",
  "online music",
  "music streaming",
  "music player",
  "download music",
  "new music",
  "music collection",
  "playlist",
  "music for workout",
  "fitness music",
  "workout music",
  "gym music",
  "music for relaxation",
  "best music for focus",
  "bodybuilding",
  "fitness",
  "workout routine",
  "gym exercises",
  "bodybuilding music",
  "fitness training",
  "weight training",
  "muscle building",
  "strength training",
  "workout motivation",
  "fitness motivation",
  "bodybuilding tips",
  "gym workout",
  "home workout",
  "ضرب",
  "ضرب بیت",
  "بیت",
  "ورسل",
  "موسیقی آنلاین",
  "پخش موسیقی",
  "موسیقی برای تمرین",
  "موسیقی برای بدنسازی",
  "موسیقی جدید",
  "آهنگ‌های ورزشی",
  "ورزش",
  "تمرین بدنسازی",
  "تمرینات ورزشی",
  "تمرینات بدنسازی",
  "بدنسازی و تناسب اندام",
  "موسیقی برای تمرکز",
  "انگیزه برای ورزش",
];
